[databases]
* = host=postgres port=5432

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = 5432
unix_socket_dir =
#user = levelcraft
auth_file = /etc/pgbouncer/userlist.txt
auth_type = md5
ignore_startup_parameters = extra_float_digits

#pool_mode = session
pool_mode = transaction
#pool_mode = statement

max_client_conn = 5000
max_user_connections = 500

default_pool_size = 50
reserve_pool_size = 10
reserve_pool_timeout = 5

#server_reset_query_always = 0


# Log settings
#admin_users = postgres,levelcraft,airflow
admin_users = postgres
verbose=0

# Connection sanity checks, timeouts

# TLS settings

# Dangerous timeouts
################## end file ##################
